version: "3.3"

networks:
  demobr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.42.0.0/16

services:
  consul:
    image: grovemountain/consul-envoy:latest
    command: ["consul","agent","-config-file=/config/server.hcl","-config-dir=/config"]
    volumes:
      - "./consul/conf.d:/config"
    networks:
      demobr:
        ipv4_address: 10.42.0.2
    ports:
      - 8500:8500

  dogs:
    image: grovemountain/picture-service:latest
    environment:
      NAME: DOGS
      VERSION: 1
      BIND_HOST: 127.0.0.1
    networks:
      demobr:
        ipv4_address: 10.42.0.3
    ports:
      - 8080:8080

  dogs_envoy:
    image: grovemountain/consul-envoy:latest
    entrypoint: /wait_for_consul.sh
    environment:
      CONSUL_HTTP_ADDR: 10.42.0.2:8500
      CONSUL_GRPC_ADDR: 10.42.0.2:8502
      SERVICE_JSON: /config/dogs-service.json
    volumes:
      - "./consul/config.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "dogs-v1"]
    network_mode: "service:dogs"

  # Define web service and envoy sidecar proxy
#  web:
#    image: nicholasjackson/upstream-echo:v0.1.8
#    environment:
#      LISTEN_ADDR: 0.0.0.0:9090
#      UPSTREAM_ADDR: localhost:9991
#      UPSTREAM_CALL: "true"
#      MESSAGE: "Hello World"
#      HTTP_CLIENT_KEEP_ALIVES: "false"
#    networks:
#      demobr:
#        ipv4_address: 10.42.0.3
#    ports:
#      - 9090:9090
#  web_envoy:
#    image: grovemountain/consul-envoy:latest
#    environment:
#      CONSUL_HTTP_ADDR: 10.42.0.2:8500
#      CONSUL_GRPC_ADDR: 10.42.0.2:8502
#      SERVICE_JSON: /config/web.json
#    volumes:
#      - "./consul/config.d:/config"
#    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
#    network_mode: "service:web"
#
#  # Define api service and envoy sidecar proxy for version 1 of the service
#  api_v1:
#    image: nicholasjackson/upstream-echo:v0.1.8
#    environment:
#      LISTEN_ADDR: localhost:9090
#      MESSAGE: "Service V1"
#    networks:
#      demobr:
#        ipv4_address: 10.42.0.4
#  api_proxy_v1:
#    image: grovemountain/consul-envoy:latest
#    environment:
#      CONSUL_HTTP_ADDR: 10.42.0.2:8500
#      CONSUL_GRPC_ADDR: 10.42.0.2:8502
#      SERVICE_JSON: /config/api_v1.json
#    volumes:
#      - "./consul/config.d:/consul/config"
#    command: ["consul", "connect", "envoy","-sidecar-for", "api-v1"]
#    network_mode: "service:api_v1"
#  


